### ISSUE TITLE
Indestructible bricks

### ISSUE THREAD

**Issue by AKryukov92** [MT-CTF/capturetheflag#101]
Currently on The Bridge map it is possible to craft Bricks block.
Bricks are much softer than cobble and don't worth the trouble.
I propose:
- make bricks indestructible by pick
- allow their destruction by shotgun
- deny their placement closer than 5 blocks to flag (it will take too much blocks to surround this area with only bricks

**Comment by afshaan4** [comment]
Yeah that would make it more interesting.

**Comment by ClobberXD** [comment]
They can be destroyed only by a shotgun? What if shotguns do not spawn anywhere in a match? As of now, I think crafting guns (of any type) has been disabled.

**Comment by AKryukov92** [comment]
If team have managed to craft enough bricks to enclose base with them, then they are worthy to have strong base, regardless of having shotgun on enemy team.

Anyway, we need to play with bricks for some time to be sure if it good change or not.

**Comment by afshaan4** [comment]
yeah, testing the changes is the best way to see if it makes sense.

**Comment by ClobberXD** [comment]
Instead of modifying an existing node, why not make a new one? @rubenwardy is already planning to add a new node called [Reinforced Cobblestone](https://github.com/rubenwardy/capturetheflag/commit/6be5478273a73bda98879686d40cf67a887bf5ad) - why not make this super-strong (if it's not that way already)?

Outright indestructible is far-fetched and too OP anyways. It should just be _very_ hard to break - 16 hits with steel pick maybe? Even obsidian is just 12 / 14 hits AFAIK...
