### ISSUE TITLE
Negative points for spawn kill

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#133]
Means that players will only use spawn killing strategically, if at all

**Comment by afshaan4** [comment]
How are you differentiating spwankilling from regular kills?

kills within a certain radius from spawn, perhaps?

**Comment by Gaara95** [comment]
afshaan4: Then again, what if a player who has not just spawned is within that certain radius, and someone from the other team gets them? It would also most probably also be counted as a "spawnkill" thus giving an innocent player doing nothing wrong negative points. How are you gonna do this Rubenwardy?

**Comment by afshaan4** [comment]
yes it would have that "bug" in it's design, but that doesn't really matter because people who capture the flag should skedaddle out of there instead of staying around and killing, and backup has to kill following enemies not the ones at their spawn.

My suggested implementation  would also make the spawn a "safe place".

**Comment by Gaara95** [comment]
True, that is what the player should do, and this would make the flag bearer go and end it faster, as the players mid map have more weapons, that being the place where most of the fight happens. Yes that would be quite a good way.

**Comment by ClobberXD** [comment]
Here are my thoughts on this:
- Adding to what @afshaan4 mentioned - disabling PvP within a _n_ block radius around spawn (enemies could still be killed within the no-kill zone) would be great. As my grandma always says, "Prevention is better than cure"...
- Meanwhile, we definitely have to come up with ways to differentiate spawn-killing from the usual kills - spawn-kill = a kill near / within team-base, where victim is weaponless and doesn't fight back. The caveat: the pros who will fight back with even wood swords, will most certainly die, but the kill won't be considered as a spawn-kill...

**Comment by afshaan4** [comment]
> The caveat: the pros who will fight back with even wood swords, will most certainly die, but the kill won't be considered as a spawn-kill...

how so? they would be in spawn radius, therefore counting as a spawnkill.
I'm saying regardless of whether they fight back or not it's still counted as a spawnkill, if it is done inside the base radius.

we don't need to disable pvp in the base radius IMO, just making it reduce your score is enough to stop the spawnkillers from doing it (their main motive is score and not causing chaos).
Also to dig in the fact that it is discouraged we should make it obvious you lose score for spawnkills, like add a warning to _random messages_ and display the score lost at the end of the game.

**Comment by ClobberXD** [comment]
> how so? they would be in spawn radius, therefore counting as a spawnkill.

Because they fight back (albeit with weak weapons)

> I'm saying regardless of whether they fight back or not it's still counted as a spawnkill, if it is done inside the base radius.

This doesn't feel right to me... A pro can just enter their base in order to not get killed, which should not be the case - a kill should be considered as a spawn-kill _only when certain criteria are met_ (apart from killing near the base).

> we don't need to disable pvp in the base radius IMO, just making it reduce your score is enough to stop the spawnkillers from doing it

You do have a point - instead of just disabling PvP, issuing negative points sends a much stronger message that spawn-killing is not tolerated. Top it up with relevant random messages and a dedicated column in the scores table for negative points, we've got ourselves a neat solution to one of the largest issue plaguing CTF at present... except for the previous issue, and we're officially back to square one again - how do we differentiate a spawn-kill from a regular one? :)

**Comment by afshaan4** [comment]
>how do we differentiate a spawn-kill from a regular one?

My proposed implementation:

kills are counted as spawnkills if the kill happens **in the victims base radius**, and **the victim did not have a weapon from the "good weapons" list**

**Comment by ClobberXD** [comment]
> kills are counted as spawnkills if the kill happens in the victims base radius, and the victim did not have a weapon from the "good weapons" list

Interesting, but what if a pro is spawn-killed (even if that involves hunting them down) right after they spawn?

Also, if a spawn-kill has been confirmed (which it should in real-time), the kills of the killer and the deaths of the victim don't increase and decrease respectively, _apart_ from issuing negative points.

**Comment by afshaan4** [comment]
>Interesting, but what if a pro is spawn-killed (even if that involves hunting them down) right after they spawn?

Iv'e no idea

**Comment by Gaara95** [comment]
How big would this "safe space" be tho? Coz spawnkilling happens in aswell as around the base, so like it shouldn't be too small or too big (losing points while trying to escape with the flag isn't the best thing)

**Comment by afshaan4** [comment]
20 to 
30 nodes?

**Comment by ClobberXD** [comment]
> 20 to 30 nodes?

That's too much IMO - 8 to 12 maybe?

**Comment by afshaan4** [comment]
yeah, i didn't realise how big 20 nodes were.

**Comment by ClobberXD** [comment]
bases are very claustrophobic at times (e.g. in the Caverns map) - and a 'safe zone' for 20 to 30 nodes would be way too over-kill :grin:

**Comment by AKryukov92** [comment]
I agree with idea of @afshaan4, but have some additions.
Kills are counted as spawnkills if all this conditions are met:
* the kill happens in the victims base radius
* the victim did not have a weapon from the "good weapons" list
* **victim doesn't have the flag**

I propose base radius to be equal to 2x(distance of jump on flat surface with sprint).

I also think that this feature should be implemented only after #72.
Otherwise, players might just continue spawn-killing and don't even realize their negative score.

**Comment by afshaan4** [comment]
>victim doesn't have the flag

we entirely forgot about that, thanks

>I also think that this feature should be implemented only after #72.
Otherwise, players might just continue spawn-killing and don't even realize their negative score.

agreed.

**Comment by ClobberXD** [comment]
My thoughts on the criteria that need to be taken into account to classify kills as spawn-kills:
- Is victim a non-participant? (maybe check if kills and capture attempts == 0?)
- Is killer killing more than `n` players in the same area?
- (To be updated)

**Comment by afshaan4** [comment]
>Is killer killing more than n players in the same area?
  Is killer killing more than n players within t seconds?

it should be like this right?: `Is killer killing more than n players in the same area? && Is killer killing more than n players within t seconds?`

**Comment by ClobberXD** [comment]
The kill would be considered a spawn-kill only if **all** the criteria are satisfied, `&&` is what I meant.

**Comment by afshaan4** [comment]
Oh, ok nvm

**Comment by tidle** [comment]
>     * Meanwhile, we definitely have to come up with ways to differentiate spawn-killing from the usual kills - spawn-kill = a kill near / within team-base, where victim is weaponless and doesn't fight back. The caveat: the pros who will fight back with even wood swords, will most certainly die, but the kill won't be considered as a spawn-kill...

maybe after this change they won't

**Comment by ClobberXD** [comment]
> maybe after this change they won't

You mean the pros won't fight back with weak weapons? IMHO, they **should** fight back, since that might be the only way to get back some good weapons from the enemy...

**Comment by ClobberXD** [comment]
It's pointless to mark this a high-priority issue, as we don't yet know how a spawn-kill should be detected...
