### ISSUE TITLE
Save 1 item after death

### ISSUE THREAD

**Issue by AKryukov92** [MT-CTF/capturetheflag#229]
**preambule**
Currently when player dies, then he loses all items from inventory. All items drops on the ground.
So if you get good sword and attack enemy, you are highly likely to lose it.
The more weapons you lose at enemy base, the more weapons your enemy can use.
Eventually, you will run out of good weapons.
To win in this situation, you will need as good weapon as you can find (probably stone). 
You need to try to kill enemy players one by one with quantity advantage.
Any good weapon looted from enemy should be stored in chest and should not be used in attacks. 
Good weapons are only for defence.

I don't like that you should not use good weapons in order to win. 
It is very counterintuitive. 
It forces me to use second-quality weapons and to do reckless suicidal attacks.

**proposal**
When player dies, he should keep 1 item from first slot of his hotbar.
It will allow players to go fighting with his preffered weapon without fear of losing it.
Strategy in the game will no longer require using weapons of secondary quality.
1 slot of hotbar should be highlighted to emphasise new rule.

**Comment by afshaan4** [comment]
>Currently when player dies, then he loses all items from inventory. All items drops on the ground.
So if you get good sword and attack enemy, you are highly likely to lose it.
The more weapons you lose at enemy base, the more weapons your enemy can use.
Eventually, you will run out of good weapons.

you realise that this cycle of losing weapons happens to both teams, so weapons keep on cycling.

this is not an unfair mechanic since the amount of good tools collected depends on the skill of the team.
