### ISSUE TITLE
Take player stats into consideration during team allocation

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#315]
Player's are evenly allocated into their teams solely on the basis of player count, without giving any weightage to their stats whatsoever. This results in a haphazard distribution of skill levels across the two teams.

Please also discuss the criteria to be taken into consideration, and other implementation details.

**Comment by AKryukov92** [comment]
Before we do any complex algorithms, I propose to allow players to change teams manually.
It is boring to play in overpowered team. Some good players might balance game by themselves.

Regarding complex algorithms.
I'd like to define "rank". It is variable associated with each player which somehow determines his efficiency in the game. It might be amount of kills, our current score, kd or [ELO](https://en.wikipedia.org/wiki/Elo_rating_system).

I have two options of distributing by rank
First is simple - to the team with lesser sum of ranks
Second is complex:
* Range players in teams by rank without new player
* Make copy of ranges and add there new player with its rank
* Take red team range without new player and compare with blue team range with new player.
* Calculate integral sum - difference between players on the same index.
* Do same for red range with new player and blue range without new player.
* Move new player to the team with lesser integral sum

When some number of good players quit, we should move players from team to team.

Is it possible to attach here real player score data? It will help to test our assumptions.
We can study matchmaking in [Teeworlds](https://github.com/teeworlds/teeworlds). It is pure pvp game with good enough matchmaking.

**Comment by ClobberXD** [comment]
> I propose to allow players to change teams manually

This will be abused to the maximum. Players will use this capability to join the stronger team in order to save themselves from certain death, and further worsen the team balance.

I see only two options here:

- If done manually, only moderators should be able to do this.
  - I personally don't prefer this solution, as moderators needn't be online 24/7, and this solution would be useless without one.
  - If there's more than one moderator online, there'll be major differences of opinion on selecting the player to change teams.
- The game calculates the team balance every time a player joins or leaves, checks team imbalance on the basis on some yet-to-be-decided criteria, and selects the player to send to the other team based on some more calculations based on the same criteria.

Feel free to discuss the criteria that'd be used for ensuring fair team allocation on player join, and determining if the teams are equally balanced.

**Comment by Gael-de-Sailly** [comment]
I am really against manual team allocation. It will create endless arguments between players willing to join the stronger team and other who want to re-balance teams.

Currently there is a (simplistic) team allocation algorithm: players are sorted by score and allocated alternatively to blue and red. It's better than nothing but here are the issues I see:

1. Score isn't very well correlated to player's skill level. A player with high score is often a pro but sometimes just a semi-noob who plays too much.
2. When there are an odd number of good players (let's say 3), the 1st and the 3rd are against the 2nd, which makes the game very difficult to win for this 2nd (it would be more balanced with 1st vs 2nd + 3rd).
3. When players join during the game, they aren't concerned by this algorithm, and join a random team. They can join the dominant team and un-balance teams even more. This is particularly true after a crash or a restart because there is no team allocation at the beginning.
4. Many players leave right after the game ended, but when they leave, they have already joined the teams for the next game. If, unfortunately, many of them are from the same team, the match becomes unbalanced.

**Comment by ClobberXD** [comment]
Agreed. Points 3 and 4 are the worst factors affecting team-balance, IMO.

**Comment by AKryukov92** [comment]
To counter point 4 we can run team allocation algorithm after 15 seconds from beginning of the match.
I think 15 seconds is enough to assume that player is very likely to stay for another match.

**Comment by AKryukov92** [comment]
Teeworlds team allocation algorithm is here: https://github.com/teeworlds/teeworlds/blob/f20f509cf26468aed67d37f9e92b36a73f176091/src/game/server/gamecontroller.cpp#L155
It moves player to other team to make score difference minimal.

**Comment by xenonca** [comment]
Tbh i think 15 seconds are probably not enough, especially if the last match has been a long one and the players want to look at the summary

**Comment by ClobberXD** [comment]
> To counter point 4 we can run team allocation algorithm after 15 seconds from beginning of the match.
> I think 15 seconds is enough to assume that player is very likely to stay for another match.

Point 4 won't be an issue if we run team-balance checks every time a player leaves, the results of which can also be used to correctly allocate another player who joins the game afterwards.

**Comment by AKryukov92** [comment]
> Point 4 won't be an issue if we run team-balance checks every time a player leaves

Players quit very often in the beginning of new match after long one. It might be possible that one player will be moved from team to team multiple times. This situation is undesirable.

Switching team in the beginning of the match will trigger map loading for player. It might cause some lag for him.

It might be ok to determine moved player, but I'm not sure that he should be instantly.
What about some countdown for such player?
Something like "You will be moved to other team in 5... 4... 3... 2... 1".

Current flag carrier should not be subject of allocation in any circumstances.
It is bad surprise to lose flag because carrier was moved to other team.

Player in combat mode introduced in #311 also should not be moved immediately.
Switching team in the middle of the fight is bad surprise too.
Such player might be moved when the fight ends.

Where do you put inventory of moved player?
We have options:
1. Place chest and store all items in it
2. Drop inventory on ground like he died
3. Put everything to former team chest
4. Move player with inventory

I think we should not move inventory to other team. Any good weapons with player is a result of team effort too.
Trivial dropping items is not very good idea too. Players will be able to pick their items back because they know where they have lost them.
Dropping inventory of moved player at the team base is bad idea too. Noobs just steal those items.
Thats why I propose placing "treasure" chest with player inventory in random location of the map.

**Comment by ClobberXD** [comment]
Fair points. What if there was a lobby where players would be taken to once the match ends? The next match would begin only after 30 seconds, and players won't be allocated into teams until then.

Also, I feel that we should keep real-time team-balancing for later, and focus on allocation on join first, as there's so much more to decide for the former.

**Comment by ClobberXD** [comment]
Here's the flow of control with respect to team allocation:

### On player join

- `on_joinplayer` callback in `ctf_pvp_engine/ctf/teams.lua` calls `ctf.autoalloc`.
- `ctf.autoalloc(name, mode)` in `ctf_pvp_engine/ctf/teams.lua`
  - `name`: Player name.
  - `mode`: Allocation mode as in `minetest.conf`. [Explanation](https://github.com/MT-CTF/ctf_pvp_engine/blob/6f5bcd05d678811c86b6836786f97f3aafa67ffe/doc_settings.md#ctf) for various allocation modes.
  - CTF overrides the mode with a value of `3`, meaning that the player will be allocated to the smallest team.

### On new match

- `ctf_match.next` in `ctf_match/matches.lua` calls `ctf_alloc.set_all`
- `ctf_alloc.set_all` just randomly shuffles players into red and blue. It doesn't even check if one team is larger than the other, in the process. o_O

### TODO

So what we need to do is to set the allocation mode to `0` to disable auto-alloc, and add code to sort the player on the basis of score (for now) in `ctf_alloc`.

Support in `ctf_pvp_engine` for an allocation mode that uses custom sorting would be great to have. That way, the code could just redefine a pre-declared sorting function, and `ctf.autoalloc` would take care of the allocation.

**Comment by AKryukov92** [comment]
> So what we need to do is to set the allocation mode to 0 to disable auto-alloc, and add code to sort the player

It sounds like workaround.

To actually solve the problem we need to modify ctf_pvp_engine.
It sounds right to implement score-based algorithm in ctf_pvp_engine, but score is managed by ctf_stats.
We have two options here:
* Move ctf_stats to ctf_pvp_engine. This way, ctf_pvp_engine will depend on ctf_stats.
* Rewrite allocation code to allow custom implementation of allocation algorithm. Something like `ctf.allocation_function = function (name) return team end`. This way, MT-CTF will depend on both ctf_pvp_engine and ctf_stats

I think that exposing allocation algorithm as an API is good idea. There are a number of other games, which might define their own allocation algorithm based on other criteria.

**Comment by ClobberXD** [comment]
Yes, it does seem like a workaround now, as we'd end up implementing our own version of autoalloc. Bad idea, sorry.

- Move ctf_stats to ctf_pvp_engine. This way, ctf_pvp_engine will depend on ctf_stats.

It doesn't sound like a good idea to move `ctf_stats` to `ctf_pvp_engine`, just because we want to make use of autoalloc. It's not right to move everything into the same mod just so that they work together. The second option is the way to go, IMO. As I too have said in my previous post, there should be a new allocation mode 4, that allows mods to define a custom sorting function.

**Comment by ClobberXD** [comment]
> Currently there is a (simplistic) team allocation algorithm: players are sorted by score and allocated alternatively to blue and red.

That happens only at the start of a new match, when all the players are allocated into new teams. The imbalance actually happens thanks to the code in `ctf_pvp_engine/ctf/teams.lua` that auto-allocates those who join in the middle of a match, to the **quantitatively smaller** team.

https://github.com/MT-CTF/ctf_pvp_engine/blob/d341978b909b9fad5133c288e01930ffeaf9a9be/ctf/teams.lua#L341-L358

**Comment by bewlay** [comment]
A bit late to the party, but I don't think moving players to the other team automatically is a good idea; I, for one, wouldn't like to be moved to one team after working towards victory of the other. Furthermore, I'd know any "secrets" of my former team, including base layout etc. Also, players quitting when their team is losing might make this feature volatile at the end of a match.

Voluntarily switching teams whenever you want also would be obviously prone to misuse.

A different idea: Currently, when a player rejoins, they are allocated to the same team they were before. Instead, they could be allocated to the weaker team (by whatever metric, and possibly only if there is a certain gap between the strengths of the two teams). This way, you could voluntarily switch teams by rejoining, but only to a (substantially) weaker team. Of course, people would have to know this; and if you're disconnecting, you might switch team unintentionally. Also, player's might try to conspire somehow to get into the team they want, but I'm not sure how they'd do this exactly.

This suggestion seems quite easy to implement. A similar, more complex, but cleaner solution would be to make people able to switch teams voluntarily like @AKryukov92 proposed, but only to the (substantially) weaker team.
