### ISSUE TITLE
Bandages 

### ISSUE THREAD

**Issue by MinetestSam** [MT-CTF/capturetheflag#334]
Since rubenwardy wants to promote teamwork I think bandages would be a good addition since the bandages could only be used to heal teammates, this should promote more communication and teamwork and even in battles teammates could come and heal there teammate.

**Comment by AKryukov92** [comment]
Bandages are not the only way to heal teammates.
In the same time, they are most complex way to heal each other in terms of communication and implementation.
I would prefer healing gun rather than bandages.

**Comment by MinetestSam** [comment]
Healing would kinda become unrealistic really

**Comment by AKryukov92** [comment]
Healing by bandages is not realistic either.
Act of applying bandages does not give any healing effect irl.
CTF is not real life simulator. It is fast paced shooter with building blocks. So I prefer solutions which keep it fast-paced, allow to shoot and to build something.

**Comment by MinetestSam** [comment]
It kinda is, bandages can be used with some dressing and be put on the wound.
https://en.wikipedia.org/wiki/Bandage

**Comment by AKryukov92** [comment]
**Act** of applying bandages doesn't heal anyway. It just allow patient body to regenerate.
Discussion about realism is not relevant to CTF at all. IRL you don't have any hitpoints, your world is not made from large cubes and you can't carry whole mountain in your backpack.

Bandages are not best way to heal yourself and your teammates. There are much more options, which are simpler than bandages and promote teamwork in the same time.

**Comment by AKryukov92** [comment]
Regarding bandages introduced in #345.
They are supposed to enhance teamplay. Keep in mind that matches are usually last for hours. Players attack each other bases multiple times. If there will be 20 bandages in one match, then they provide teamplay only for one (first) attack. It doesn't sound very cooperative.
That's why they should be given to every player on respawn.

I have no viable ideas about crafting recipes. We can't use dirt or stone for bandages. We could probably use leaves. But I don't think it is good idea because there are no leaves on some maps. Trees will not grow, grass will not grow too.

In addition I thought about dropping cloth on death. It is like gathering pieces of clothes from dead. But this is not good solution because it helps stronger team. Imagine two players standing on enemy spawn and killing everyone on sight AND healing by it.
Weaker team respawns more often than stronger team. Giving bandages to them will help them to repel the attack.
