### ISSUE TITLE
Traps

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#35]
Traps have been suggested multiple times.

**Comment by Calinou** [comment]
My suggestions:

- **Landmine**
  - Can be found in chests
  - When enemy steps on it, explodes and causes damage to the player who stepped on it
  - May be too resource-intensive to detect players stepping on it

- **Fake cobble**
  - Can be found in chests
  - Looks like cobble, but hurts enemies who dig it (only enemies, not teammates)

**Comment by the1glorfindel** [comment]
fall through dirt, you can make a deep moat around your base and cover it with the dirt so people who fall in die.

**Comment by Dragonop** [comment]
I think the texture for traps should clearly point out that it's a trap. This would make attacking the enemy base at night more dangerous (if it has traps of course)

**Comment by rubenwardy** [comment]
You should be able to tell it's a trap, but it should also be fairly subtile in that it's easy to miss if you're distracted by fighting.

**Comment by Dragonop** [comment]
I agree, what kind of traps are you going to add? 
I think all the traps should be crafteable, and only a few, like fake cobble should be found in chests.
Here my ideas:
Fake cobble: A thin layer that you place on top of nodes (like microslabs, 1 pixel tall). Useful for making hidden holes or hidden doors.
Fake wood door: A door that nobody is able to open.
Fake flag: Tricking the enemy team is always fun.
Poison apple/old apple: A yellowish apple that deals 1 damage when used.
A potion/item to make your nametag invisible for some seconds. Might require playereffects.

**Comment by AKryukov92** [comment]
Yesterday I have seen traps, which look like 2x2x2 hole in dirt. I personally get in such trap several times by accident. And I have killed several persons in such traps. Very annoying for victim, but very clever.
If someone place "spikes" on the bottom of such trap, it will really hurt. Spikes themselves might look very obvious.
Block, which look like grass, but is not solid (lets you fall down trough) will be cool too. It would be minor but annoying obstacle. With spikes, it will rock.
Quicksand (and quickgravel) might be good option too because of slowing down feature.
