### ISSUE TITLE
Tools are auto-repaired when placing in chest in a certain way

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#418]
![](https://cdn.discordapp.com/attachments/475323872644956170/595704602754678928/Chest.gif)

(Image by Lone_WolfHT)

**Comment by ClobberXD** [comment]
@LoneWolfHT Is this bug still relevant?

**Comment by LoneWolfHT** [comment]
It seems to be moving the correct items now

**Comment by LoneWolfHT** [comment]
Tested on the server too. Can't reproduce

**Comment by shivajiva101** [comment]
The stack is placed in the chest and deleted from the player inventory, if the stack loses any of its properties then it's being handled wrong elsewhere in code, this is a simple transfer a copy and delete the original. I presume whatever was done to break it has been fixed now because it can't be reproduced and should never have needed handling in the first place :man_shrugging:
