### ISSUE TITLE
Overhaul respawn immunity

### ISSUE THREAD

**Issue by Cahrs** [MT-CTF/capturetheflag#460]
**Problem:**
Currently respawn-immunity often leads to extremely unfair battles near the enemy base, often making flag-capping harder (and take longer) then it should be. In fact, the 30 seconds of immunity is long enough to get to mid on most maps (dependent on how players have changed the terrain over the course of the battle) and get a free hit on the enemy, giving them a huge immediate advantage

**Possible Solutions:**
1) decrease immunity time to 5 seconds or so and disable that player from damaging anyone else during that period, drawback being that during a raid by enemy players they still have enough time to get behind the enemy to take them out without suffering damage.

2) Keep the current immunity-time and implementation, but change it so that every x seconds during immunity time it checks that players inventory for an item from the "good-weapons" list, and if it returns true revoke immunity immediately, drawbacks being more complexity.

**Comment by Cahrs** [comment]
If the latter is implemented, what are thoughts on checking the entire players inv vs just checking the players hotbar?

**Comment by ClobberXD** [comment]
Immunity is just 15 seconds at the moment:

https://github.com/MT-CTF/capturetheflag/blob/2ae401d4f50ed9e8c7fc7fb6cc7bb77335c07cc1/mods/ctf/ctf_respawn_immunity/init.lua#L3

**Comment by LoneWolfHT** [comment]
I think a ~5 second respawn delay would work a lot better.
Reducing the immunity time down to 8-10 sounds fine.
Decreased score when killing a player near their base might be a neat addition

**Comment by ClobberXD** [comment]
Respawn immunity exists to give the defending team a head-start in order to combat spawn-killing. 

> disable that player from damaging anyone else during that period

That'd be unbalanced. The player should have the full freedom to terminate their immunity before it ends, and not be forced to go through the full x seconds of immunity for no reason. Sacrificing one's immunity for the greater good of their team is a perfectly valid strategy. Again, the whole point of respawn immunity is to give the defenders a head-start. This can be likened to the fact that a team/kingdom is stronger at their home base, which is popularly referred to as "home advantage".

Even if a player has good weapons, they might need time to run out and gather stuff, without which they might not survive against the horde of enemies in hot pursuit (I myself have been in this situation a lot).

**Comment by MinetestSam** [comment]
I firmly disagree with both the suggestions.
1. If the respawn immunity is reduced to 5 seconds then the chances of excessive spawn killing would increase as the defenders would have no advantage and nor the time to escape

2. The good weapons list is quite subjective on different maps. For example, on maps where you can get diamonds, like Caverns, people would always prefer a diamond sword over an iron sword but maybe one team has only got iron swords to fight with against diamond swords. The defending team would lose because iron swords would be in that 'good weapons' list and they will lose their immunity which would have helped them in battle.
In maps where you get iron tools from spawn like Ice Age, people would spawn kill endlessly as there would be no respawn immunity.
