### ISSUE TITLE
Re-consider pro-chest requirements

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#519]
(I initially thought of re-opening a #80 for this, but never mind...)

#### Rationale

- If a player is even fairly skilled, they can easily rake up hundreds of points within no time.
- Score can never go down, so once a player crosses 1000 score, their K/D would be the deciding factor.
  - But K/D can't be the only factor, as it can fluctuate wildly when the number of deaths are low (i.e. single or double digit; from 0 - 99). Hence the need for a hard lower bound on grounds of score.
- The current K/D requirement of 1.5 is reachable by almost everyone who plays on a PC, including even the most mediocre players. IMO, there's no point in having a "pro" section if everyone with a PC can access it (we might as well rename it to "PC Master Race" section).

#### Proposition

IMO, the ideal requirement for pro-chest access would be:

- 10000 score
- 3 K/D

The proposed requirement is open to suggestions arising from the discussion that'll ensue.

**Comment by Thomas--S** [comment]
I'd support the proposal to increase the score, but I'm strongly opposed to increase the K/D, especially to such a high value.

Having such a high K/D limit supports a playing style in which players focus on their own K/D instead of helping the team. This is often very counterproductive because it would often help the team greatly to use rather cheap weapons (stone swords) to fight back a rather strong opponent, but this also includes a low K/D; although this strategy often turned around the game.

I think access to the pro chest shouldn't depend on the K/D, but mainly on score. I'm fine with a K/D limit of 1.5, so that not everyone who plays long enough has access, but I don't think this limit should be raised.

**Comment by ClobberXD** [comment]
> Having such a high K/D limit supports a playing style in which players focus on their own K/D instead of helping the team

My objective is to prevent reckless players from accessing the pro-section and wasting weapons and other resources, thereby reducing their team's chances of victory. But I agree that too high a K/D requirement like 3 can lead to players refraining from helping their team, and tending towards preserving their K/D more. What do you think about a K/D requirement of 2? It's an increase, but it's pretty close to the current requirement of 1.5. IMO, 2 kills for each death is a very "accessible" ratio for pros.

**Comment by Thomas--S** [comment]
I can understand your objective and I support this.

However, I think that even a K/D of 2 is a bit too much. There are many matches where I don't have a K/D higher than 1.5 because I used the strategy described above. (This strategy usually also helps to fill the team chest.)

I think that raising the score requirement to 10000 will probably already help enough. I'd suggest to try it with only this change and then – if necessary – do further adjustments.

**Comment by ClobberXD** [comment]
Ok, we'll bump only the score requirement for now, and reconsider the K/D requirement later.

**Comment by LoneWolfHT** [comment]
I'd be fine with a K/D raise to 1.7. But probably not any higher

**Comment by ClobberXD** [comment]
1.7 is a weird number, and is also too specific. ;)

But we've decided to leave the K/D requirement alone for now.

**Comment by ClobberXD** [comment]
I'd prefer this to be done in time for 2.0.0

**Comment by JostP** [comment]
What about having pro-pro-chest inside pro chest (something like 5 slots) where K/D would be 2.5 or more and 10000+ points?
Epic weapons can be stored there like grenades, SMG, mese swords from rubenwardy's maps or plain battle's meses and so on.

**Comment by Thomas--S** [comment]
> What about having pro-pro-chest inside pro chest (something like 5 slots) where K/D would be 2.5 or more and 10000+ points?
Epic weapons can be stored there like grenades, SMG, mese swords from rubenwardy's maps or plain battle's meses and so on.

I don't think this is a good idea either because this also supports a gameplay style in which players are focussed on their K/D instead of helping the team.
If we want to make a pro pro chest (which I don't really think would be a good idea), then we should only use the score as a limiting factor.

**Comment by ClobberXD** [comment]
I'm not in favour of adding more sections and essentially dividing the players into categories.

**Comment by MinetestSam** [comment]
I agree with Thomas the score threshold should be increased. I would also suggest adding  number of captures or attempts to this "pro-ness" factor too. This would make players go and try to capture the flag or attempt to capture it rather than just sitting back and focusing on their K/D or score.

**Comment by ClobberXD** [comment]
I too would like to take captures and attempts into consideration, in the long term. :+1:

**Comment by Thomas--S** [comment]
I also appreciate the idea of taking captures and attempts into consideration.

However, I'm not sure if it is a good idea to take the captures and attempts into consideration explicitly in the is_pro function.
Instead, for reasons of clarity and simplicity, I'd suggest to increase the capture and attempt score values slightly (probably depending on the match length and/or the number of online players).

**Comment by MinetestSam** [comment]
>Instead, for reasons of clarity and simplicity, I'd suggest to increase the capture and attempt score values slightly (probably depending on the match length and/or the number of online players).

I think then you'd be ultimately counting the score and making it the threshold. Also as you mentioned in another post, matches can be made artificially long and sometimes the number of players may also not be "skilled" enough to protect their flag.
