### ISSUE TITLE
Overlapping HUD elements

### ISSUE THREAD

**Issue by xenonca** [MT-CTF/capturetheflag#611]
As can be seen in the screenshot the health hearts overlap with the breath bubbles because the knight class adds some lives to the player.
![SCS](https://user-images.githubusercontent.com/36995016/81054307-d9627a80-8ec6-11ea-885f-5c84068160fb.png)

**Comment by ClobberXD** [comment]
I'd really prefer a better approach to this than statbars and engine modifications - an approach that has better granularity. I'm thinking, `hudbars`. @rubenwardy Was `hudbars` removed because they were laggy?

Or... we could just move the breathbar above the health bar. That'd work just as well, as we're already modifying `builtin`.

Another, rather high-IQ alternative is to display health textually (as a percentage or raw HP), but that'd be pretty ugly - we don't roll like that.

**Comment by xenonca** [comment]
I think we did, as a player's hearts now represent the percentage of health they have.

**Comment by LoneWolfHT** [comment]
Yeah. I think so.
Adding hudbars would be nice though. It should work ok for this too

**Comment by rubenwardy** [comment]
Yeah, hudbars were removed due to lag. There's been engine HUD improvements since
