### ISSUE TITLE
Classes: Consumable class-items and anti-abuse discussion

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#630]
Players change to another class and back, to re-stock on their class items. While this can be considered abuse in a way, I realised that unlike knights, most other classes mostly rely upon *consumable* items like bandages, rockets, grenades, etc. - once they run out of their consumable class-items, they're out-of-action unless they restock (by dying, or by using exploits like this). While I'm all for preventing abuse, I also can't help but feel like there's no other way for there classes to restock their consumables, apart from committing suicide. These are the solutions I can immediately think of:

- Make the primary class-items non-consumable - a healing "wand" instead of bandages, for example. Yes, this idea very closely resembles #333, and also makes me sound like an idiot. But this actually seems like a good idea to me now.

  We've recently increased the medics' bandages from 20 to 50, but they'll still be fully consumed within minutes, in an "epic" match. Once their bandages run out, medics are sitting ducks, and won't be able to help the team much apart from speeding up the regen a little bit. But if they have an "infinite" source of meds, they can keep doing their thing.

- Make kills drop a couple of class-item consumables of the killer's class. e.g. if a medic kills an enemy, they get back 2-3 bandages (directly to their inv, to prevent other players from picking them up). This is a much simpler solution than the previous one, and I personally prefer this one for its simplicity.

Once we take care of the consumables situation, we can go ahead and prevent abuse of class-items by maybe forcing a cooldown after each class change.

Inputs, suggestions, and alternatives appreciated.

**Comment by Thomas--S** [comment]
>  Make the primary class-items non-consumable - a healing "wand" instead of bandages, for example. Yes, this idea very closely resembles #333, and also makes me sound like an idiot. But this actually seems like a good idea to me now.

To be honest, I don't like the idea of a healing "wand" very much. Instead, I'd suggest to add an inventory slot (that provides the consumables indefinitely) to the flag formspec, so that classes can restock their consumables for free at the flag.

>  Make kills drop a couple of class-item consumables of the killer's class. e.g. if a medic kills an enemy, they get back 2-3 bandages (directly to their inv, to prevent other players from picking them up). This is a much simpler solution than the previous one, and I personally prefer this one for its simplicity.

I think it shouldn't be the job of a medic to kill another player just to have enough consumables available.

**Comment by ClobberXD** [comment]
> I'd suggest to add an inventory slot (that provides the consumables indefinitely) to the flag formspec, so that classes can restock their consumables for free at the flag.

That's actually a neat idea.

**Comment by xenonca** [comment]
I can imagine that medics will then just fill up their inventory (or the chest) with bandages which would lead to a little mess. Especially since non-medics would kind of have unlimited access to bandages too if there's a medic putting bandages back to the team chest.
One option would be to set an individual cool-down to that bandages-slot which gives you, say 50 bandages every 2 minutest or so (that can be tweaked as needed).
Another option could be adding such a slot/button (with cool-down) to the medics inventory. However I have no idea how or even if that's possible, to modify a player's inventory per class. That way the player would not need to run back to the flag every time (unless that's a wanted behavior, but then they could also just keep restocking by changing class). Just need a safe spot to access your inventory and restock. Maybe this could be done as a craftitem that is only craftable for medics and needs no resources to craft?

**Comment by ClobberXD** [comment]
The ability to put bandages in the chest is a concern, as it would occupy space that could otherwise be used for more precious items like weapons. But medics filling up their own inventory isn't much of an issue - they're the ones losing out on inv. space, and no one else would be affected by this situation. On the flip side, inv slots, buttons, et al are pretty complicated to implement free-of-bugs - it'll take time.

I'm thinking of a much simpler solution - just make the bandage "non-consumable" while using. The implementation is brutally straight-forward - simply return the original wielded itemstack in on_use instead of returning `stack:take_item()`. This would just solve the medic-bandages aspect of the overall consumables issue, but bandages are also the ones that run out the fastest. Medics would only get one single bandage, but it'll last forever. It sounds pretty unrealistic, but it saves us the hassle of implementing a way to replenish bandages, and making it abuse-proof. But this idea brings us back to square one, as this is conceptually the same as a "healing wand". :)

@Thomas--S, may I know why you're uncomfortable with the idea of a healing wand?

**Comment by Thomas--S** [comment]
I can't specify exactly why I don't like the idea of a healing wand, but I think that the most important point is the realism.
Choosing the healing wand option would be only because it is easier to implement, but I think that gameplay decisions should not be primarily based on how hard to implement something is.
Furthermore, I think that a healing wand and replenishable consumables aren't the same from a gameplay perspective because even when the consumables are replenishable (near-)indefinitely, you have to take care about refilling them and can't just rely on a magic tool.

**Comment by ClobberXD** [comment]
> Furthermore, I think that a healing wand and replenishable consumables aren't the same from a gameplay perspective because even when the consumables are replenishable (near-)indefinitely, you have to take care about refilling them and can't just rely on a magic tool.

Ah, I see where you're going with this. You're emphasising on the player needing to refill their consumables, instead of the consumables not depleting at all. That's a very fair point.

**Comment by ClobberXD** [comment]
I was originally under the impression that we'll have to fix this in time for 2.0.0, hence my concerns about the difficulty in implementation. But I think this can wait until 2.1.0.
