### ISSUE TITLE
[Feature Request] Make PRO players able to start a vote to skip the map (grant them "Vote_starter" privilege)

### ISSUE THREAD

**Issue by ghost** [MT-CTF/capturetheflag#668]
**Hello,**
**I have a request,**
**First-off**,I'm not a pro player,
**but** given the time and effort  these players spend to get that status,
they should get something worth it("the extra space in the team chest isn't worth it and I don't even think anybody uses it and to be honest(I thought it had something special but some other player told me it's empty)")
**So** my way of solving that is giving these players the "Vote_starter" privilege,that means they can start a vote to skip the map if they want,
**And No**, I don't think they can abuse it,because other player have to agree for the skip to happen.

**Comment by LoneWolfHT** [comment]
vote_starter isn't for skipping maps you don't like, if players don't like a map they should request it be removed.

The pro chest starts out empty at the beginning of the match, but as the match goes on teams acquire valuable items that they want to make sure only go to pro players, the pro section of the chest is how they do that

**Comment by Nifty-Neutron** [comment]
> vote_starter isn't for skipping maps you don't like, if players don't like a map they should request it be removed.
> 
> The pro chest starts out empty at the beginning of the match, but as the match goes on teams acquire valuable items that they want to make sure only go to pro players, the pro section of the chest is how they do that

Well what if the  players think that the map is ok but they want to just skip it for that time because they are not feeling like playing it,or they are short on time and they know that the map takes ages to finish??
Also,Only pro players can put items in the pro section so if a less-experienced player(like me) likes to insure that the mese sword  
he has falls in the right hands(the hands of a pro),how would he do that?
he can throw it on the ground for that player to pick,but what if some other player(from another team) picks it up??
anyways huge thanks for the work you put on this server,
much appreciated.
