### ISSUE TITLE
Classes Problem

### ISSUE THREAD

**Issue by KodaTheGuy** [MT-CTF/capturetheflag#703]
The cobblestone that is given to medics when they join the game can be duplicated, the only way I know of this problem is because I used it today. I used two accounts and kept on joining on both accounts and stored all the cobble into the chest. I suggest making it a kit-only item?

**Comment by KodaTheGuy** [comment]
@LoneWolfHT

**Comment by LoneWolfHT** [comment]
If I do that it'll probably seriously mess up maps like Caverns/Tunnels. Where you do a lot of stuff with cobble

Since stone is more common than dirt on pretty much all maps I'm not too worried about this. I encourage putting it towards the construction of a larger team base if you have the patience
