### ISSUE TITLE
Game Objectives

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#71]
One of:

1. normal game
2. power shields  #69 
3. kill a random player?

**Comment by ClobberXD** [comment]
(Moved from #190)
****

I've seen quite a few PvP games in which there are many "game-types" out of which one is randomly selected for the current match. I propose to make CTF one of the game-types, so there'd be game-types like
- Team Death-match
  - Two teams go on a killing spree, and the team with the higher total score at the end of `t` minutes wins.
  - Players will be given a default set of weapons on (re)spawn, to keep things equal.
  - Maps like `Intervention in the IceAge` are ideal for this type.
- Last man standing
  - No teams, it's all vs. all. Players would be spawned at random places throughout the map (surface only).
  - Players will be granted a set of default weapons on (re)spawn.
  - Keep clobbering for `t` minutes. Player with the highest score wins.
- Capture the flag
  - The original CTF experience.
  - Instead of one capture to end, it could be modified so that the team which reaches 5 captures first, wins.
- (More to come)

Yes this certainly makes CTF (the game) more complicated, but I feel that it will be very engaging and thrilling for the players.

****

I've already gotten a few ideas about the implementation:
- Game-type could be set using a `game_type` field in `map.conf`.
- All of the suggested functionality can either be added to `ctf_match` itself, or can become a separate mod (`ctf_game_types` maybe?).
- Some of the player stats (like `kills`, `deaths`, `K/D`, etc.) will persist across all game-types, while those like `captures` and `attempts` would be game-type-specific.

Will proceed if this is agreed to be a good concept :)

**Comment by afshaan4** [comment]
> Team Death-match
 Two teams go on a killing spree, and the team with the higher total score at the end of t minutes wins.
 Players will be given a default set of weapons on (re)spawn, to keep things equal.

instead of players being given a set of default weapons, we could add "weapon spawn points" where if you walk into it you pick up the weapon (like in many shooters), and the spawn point refreshes every `t` seconds.

But to make my suggestion a practical thing we would need:
* a way to stop players from camping the spawn points
* maps would need to be redesigned to be smaller and more vertical so moving between areas doesn't     
  take forever
* player movement speed would need to be changed?

**Comment by ritschwumm** [comment]
camping at spawn-points might not be a problem - you'd be an easy target if you did

**Comment by afshaan4** [comment]
>a way to stop players from camping the spawn points

you could do it like this:

https://youtu.be/OLztpV6lLKg

**Comment by ClobberXD** [comment]
I'm starting to think that this feature should be a part of `ctf_pvp_engine`, as it's the logical thing to do...
