### ISSUE TITLE
Only add death to rank when killed by player, suicide or combat log

### ISSUE THREAD

**Issue by Code-Sploit** [MT-CTF/capturetheflag#861]
Currently when you die, no matter why, you get +1 death in your rank.
I think you should only get +1 death in your rank when killed by player, suicide or combat log.
Because, for example, if you fall into lava, deadly water or any other of that CTF stuff you get a death.
Your KD can get easily ruined by playing on the 'Abandoned Islands' map if you aren't good in parkour.

Hope this will be implemented!

P.S: I can also try to code this myself, i'm a good coder ;).

**Comment by LoneWolfHT** [comment]
K/D is partly used to limit access to the pro side of the team chest. If you're the kind of person that falls and dies a lot you probably shouldn't take anything from the pro chest because there's a good likelihood of you falling and losing it before it can be used.
If you didn't get deaths for falling and dying then the system wouldn't really be able to detect that.
